# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_utc', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('score', models.IntegerField()),
                ('subreddit', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
