# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_submission_elo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='elo',
            new_name='trueskill',
        ),
    ]
