# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20170925_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='trueskill',
        ),
        migrations.AddField(
            model_name='submission',
            name='ts_mu',
            field=models.DecimalField(decimal_places=5, default=25, max_digits=9),
        ),
        migrations.AddField(
            model_name='submission',
            name='ts_sigma',
            field=models.DecimalField(decimal_places=5, default=8.333, max_digits=9),
        ),
    ]
